# Site Settings
title: Spacious
email:
description: >
  Spacious bootstrap & Jekyll 4 template
baseurl: ""
url: "http://localhost:4000"
twitter_username:
github_username:  pmsaue0
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM