# Site Settings
title: Adam J Gomez
email:
description: >
  Portfolio of Adam J Gomez
baseurl: ""
url: "http://localhost:4000"
twitter_username:
github_username:  adamjgomez
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
