# Site Settings
title: Neo
email: psauerbeck@gmail.com
description: >
  Neo
baseurl: "/neo"
url: "http://pmsaue0.github.io"
twitter_username:
github_username:  pmsaue0
# Build Settings
sass:
  sass_dir:
include: ['_pages']
kramdown:
  input: GFM