# Site Settings
title: Spacious
email:
description: >
  Spacious bootstrap & Jekyll 4 template
baseurl: "/spacious"
url: "http://pmsaue0.github.io"
twitter_username:
github_username:  pmsaue0
# Build Settings
sass:
  sass_dir:
include: ['_pages']
kramdown:
  input: GFM