# Site Settings
title: Adam J Gomez
email:
description: >
  Porfolio of Adam J Gomez
baseurl: "/portfolio"
url: "http://adamjgomez.github.io"
twitter_username:
github_username:  adamjgomez
# Build Settings
sass:
  sass_dir:
include: ['_pages']
kramdown:
  input: GFM
